### ISSUE TITLE
python stop working while set Chinese word

### ISSUE THREAD

**Issue by eromoe** [pytries/datrie#47]
![image](https://user-images.githubusercontent.com/3938751/34091643-0cc34906-e3fa-11e7-96be-e447ca3a2474.png)

My code like:

```
    text = htmls_2_text(input_dir)
    sentences = text_2_sentences(text)
    wf = count_wrodfreq_range(sentences)

    print('Init trie')

    trie = datrie.Trie(''.join(set(text)))

    print('Update counter dict:', len(wf))
    for k, v in wf.most_common(3000):
        try:
            trie[k] = v
        except Exception as e:
            print(k, v)

    # trie.update(dict(wf.most_common(3000)))
```

Can't catch exception,  It didn't happend when add 1000 word,  sometime happen when add 2000 word(but sometimes not) . 

I tried many times, only occur below error twice, 
```
Traceback (most recent call last):
  File "build_dict.py", line 124, in <module>
    build_freq_trie(input_dir, freq_trie_path)
  File "build_dict.py", line 113, in build_freq_trie
    trie.update(dict(wf.most_common(9000)))
  File "src/datrie.pyx", line 80, in datrie.BaseTrie.update (src/datrie.c:2532)
  File "src/datrie.pyx", line 686, in datrie.Trie.__setitem__ (src/datrie.c:12895)
IndexError: list assignment index out of range
```

## test data

text : 
[test.txt](https://github.com/pytries/datrie/files/1566760/test.txt)

wf (please use `pickle.load` ) :
[freq.txt](https://github.com/pytries/datrie/files/1566762/freq.txt)

**Comment by eromoe** [comment]
I think the problem is by encoding problem

```
trie['今天天气真好'] = 333
trie['今天好'] = 333
trie['今天阿萨德'] = 333

print(trie.items())

# wrong char,  and not three word
[('今义义傲兢于', 333), ('今义于', 333)]
```

And I also got once,
```
[('今义', 333), ('今义义傲兢于', 333), ('今义于', 333)]
```

The randomness frustrate me ...
